import type { Builder, Organization, Member, BuildLog } from '@/types'

export const mockOrganizations: Organization[] = [
  {
    id: 'org-1',
    name: 'Acme Corp',
    slug: 'acme-corp',
    builderCount: 5,
    memberCount: 3,
    totalMinutes: 15420,
    monthlyMinutes: 2340,
    createdAt: new Date('2024-01-15'),
    members: [
      {
        id: 'user-1',
        name: 'John Doe',
        email: 'john@acme.com',
        role: 'owner',
        joinedAt: new Date('2024-01-15'),
      },
      {
        id: 'user-2',
        name: 'Jane Smith',
        email: 'jane@acme.com',
        role: 'admin',
        joinedAt: new Date('2024-01-20'),
      },
      {
        id: 'user-3',
        name: 'Bob Johnson',
        email: 'bob@acme.com',
        role: 'member',
        joinedAt: new Date('2024-02-01'),
      },
    ],
  },
]

export const mockBuilders: Builder[] = [
  {
    id: 'builder-1',
    name: 'production-builder',
    organizationId: 'org-1',
    size: 'large',
    region: 'us-east',
    status: 'idle',
    cacheSize: 12.5,
    maxCacheSize: 50,
    platform: ['linux/amd64', 'linux/arm64'],
    createdAt: new Date('2024-01-20'),
    lastUsed: new Date('2024-02-15T10:30:00'),
    buildCount: 342,
    totalMinutes: 8920,
  },
  {
    id: 'builder-2',
    name: 'staging-builder',
    organizationId: 'org-1',
    size: 'medium',
    region: 'us-east',
    status: 'building',
    cacheSize: 8.2,
    maxCacheSize: 25,
    platform: ['linux/amd64'],
    createdAt: new Date('2024-01-22'),
    lastUsed: new Date('2024-02-15T14:25:00'),
    buildCount: 156,
    totalMinutes: 3120,
  },
  {
    id: 'builder-3',
    name: 'dev-builder',
    organizationId: 'org-1',
    size: 'small',
    region: 'us-west',
    status: 'idle',
    cacheSize: 3.8,
    maxCacheSize: 10,
    platform: ['linux/amd64'],
    createdAt: new Date('2024-02-01'),
    lastUsed: new Date('2024-02-14T16:45:00'),
    buildCount: 89,
    totalMinutes: 1240,
  },
  {
    id: 'builder-4',
    name: 'ci-builder-1',
    organizationId: 'org-1',
    size: 'medium',
    region: 'eu-central',
    status: 'idle',
    cacheSize: 15.3,
    maxCacheSize: 25,
    platform: ['linux/amd64', 'linux/arm64'],
    createdAt: new Date('2024-02-05'),
    lastUsed: new Date('2024-02-15T09:15:00'),
    buildCount: 203,
    totalMinutes: 4890,
  },
  {
    id: 'builder-5',
    name: 'experimental',
    organizationId: 'org-1',
    size: 'xlarge',
    region: 'us-east',
    status: 'offline',
    cacheSize: 2.1,
    maxCacheSize: 100,
    platform: ['linux/amd64', 'linux/arm64'],
    createdAt: new Date('2024-02-10'),
    lastUsed: new Date('2024-02-12T11:20:00'),
    buildCount: 12,
    totalMinutes: 340,
  },
]

export const mockBuildLogs: BuildLog[] = [
  {
    id: 'build-1',
    builderId: 'builder-2',
    builderName: 'staging-builder',
    status: 'building',
    duration: 0,
    image: 'acme/web-app:staging',
    startedAt: new Date('2024-02-15T14:25:00'),
  },
  {
    id: 'build-2',
    builderId: 'builder-1',
    builderName: 'production-builder',
    status: 'success',
    duration: 124,
    image: 'acme/api:v2.3.1',
    startedAt: new Date('2024-02-15T10:30:00'),
    completedAt: new Date('2024-02-15T10:32:04'),
  },
  {
    id: 'build-3',
    builderId: 'builder-4',
    builderName: 'ci-builder-1',
    status: 'success',
    duration: 89,
    image: 'acme/worker:latest',
    startedAt: new Date('2024-02-15T09:15:00'),
    completedAt: new Date('2024-02-15T09:16:29'),
  },
  {
    id: 'build-4',
    builderId: 'builder-3',
    builderName: 'dev-builder',
    status: 'failed',
    duration: 45,
    image: 'acme/frontend:dev',
    startedAt: new Date('2024-02-14T16:45:00'),
    completedAt: new Date('2024-02-14T16:45:45'),
  },
  {
    id: 'build-5',
    builderId: 'builder-1',
    builderName: 'production-builder',
    status: 'success',
    duration: 156,
    image: 'acme/web-app:v1.5.0',
    startedAt: new Date('2024-02-14T14:20:00'),
    completedAt: new Date('2024-02-14T14:22:36'),
  },
]
