name: On Push

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-push:
    uses: builderhub/actions/.github/workflows/build-push-image.yaml@main
    with:
      image-name: builderhub-console
      local-image-name: builderhub-console
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
      id-token: write
