name: On Push

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-push:
    uses: builderhub/actions-internal/.github/workflows/build-push-image.yaml@main
    with:
      image-name: build-console
      local-image-name: builderhub-console
    secrets:
      registry-password: ${{ github.token }}
    permissions:
      contents: read
      packages: write
